### PR TITLE
Set max bounds to hearing map

### PR DESCRIPTION
**Pull request by JsseL**
Properly set max bounds makes sure that the hearing map can't be
accidentally scrolled or zoomed out of the Helsinki area.

This should improve the user experience of the map component.

Refs: #204

### CODE REVIEW

**Comment by JsseL** [comment]
I modified the restricting bounding to be the roughly the Helsinki area instead of the specific hearing area. This change made the map actually pretty nice to use.

In addition to the bounding box, I added min zoom level (see the second commit).

**Comment by JsseL** [comment]
### Note
Defined bounds for Helsinki are just rough estimates which felt ok. If someone can provide more accurate coordinates, feel free to inform me and I'll add them.

**Comment by Rikuoja** [comment]
```
                [60.1, 24.75],  // SouthWest corner
                [60.35, 25.3]  // NorthEast corner
```

would seem like suitable bounds to me.

**Comment by Rikuoja** [comment]
Otherwise LGTM :)

**Comment by JsseL** [comment]
Changed bounds to the ones you suggested. They indeed felt good!

**Comment by JsseL** [comment]
I think we got the coordinates a bit wrong after all. The bounds are too restrictive at the moment. So this needs small fine tuning of the bounds.

**Pull request merged**
