### PR TITLE
KER-229 Eslint configuration enhancements

### PR DESCRIPTION
**Pull request by mikkojamG**
# KER-229 Eslint configuration enhancements

Updating Eslint rules to be in line with other Ratkaisutoimisto frontends.

- Updating `.eslintrc.json`, add new plugins (import, prettier, sonarjs) and rules
- Fixing lint errors, some would be to big of an effort to fix on one go so ignoring for now
- Updating `.editorconfig` and adding `.prettierrc`. Formatting documents
- Change files with JSX code to `.jsx` format
- Remove unnecessary `.travis.yml`

### CODE REVIEW

**Review by arpargo — APPROVED** [review]
LGTM

**Comment by arpargo** [comment]
Two errors encountered when running tests:
```
 TypeError: Cannot set properties of null (setting 'changeLanguage')

      33 |       const changeLanguageMock = jest.fn();
      34 |       const element = getWrapper();
    > 35 |       element.instance().changeLanguage = changeLanguageMock;
```

And 

```
    TypeError: Cannot set properties of null (setting 'handleClick')

      111 |       const handleClickMock = jest.fn();
      112 |       const element = getWrapper();
    > 113 |       element.instance().handleClick = handleClickMock;
```

**Comment by mikkojamG** [comment]
> Two errors encountered when running tests:
> 
> ```
>  TypeError: Cannot set properties of null (setting 'changeLanguage')
> 
>       33 |       const changeLanguageMock = jest.fn();
>       34 |       const element = getWrapper();
>     > 35 |       element.instance().changeLanguage = changeLanguageMock;
> ```
> 
> And
> 
> ```
>     TypeError: Cannot set properties of null (setting 'handleClick')
> 
>       111 |       const handleClickMock = jest.fn();
>       112 |       const element = getWrapper();
>     > 113 |       element.instance().handleClick = handleClickMock;
> ```

Fix https://github.com/City-of-Helsinki/kerrokantasi-ui/pull/964/commits/f5938572e9756f7eadbf763b7dfada3954aecee3

**Comment by arpargo** [comment]
LGTM

**Review by arpargo — APPROVED** [review]

**Pull request merged**
