### PR TITLE
Fix warnings about bad DOM in SortableCommentList

### PR DESCRIPTION
**Pull request by juhana**
Removes console warnings about invalid DOM as per https://github.com/yahoo/react-intl/issues/286#issuecomment-236348944

### CODE REVIEW

**Comment by Rikuoja** [comment]
I'm not getting any console warnings, what are the steps to reproduce the problem?

**Comment by juhana** [comment]
If you open any page with a select element, for example any hearing with comments, you get:

```
Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
Warning: Only strings and numbers are supported as <option> children.
Warning: validateDOMNesting(...): <span> cannot appear as a child of <option>. See SortableCommentList > option > FormattedMessage > span.
Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
```

The warnings are generated by warning.js, they don't show in production. The DOM is invalid because `FormattedMessage` wraps the text in `<span>` inside select options.

**Comment by Rikuoja** [comment]
Ah, now that you mention it I have been wondering about them. Currently I cannot get the development mode to run locally, so didn't get those warnings. Looks good!

**Comment by Rikuoja** [comment]
Ah damn. 

Snapshots fail and lint fails, so these will still need to be fixed :(

**Comment by juhana** [comment]
Right, sorry, I don't know how to update the snapshots.

**Comment by Rikuoja** [comment]
Ah @jonnetanninen will have to do that I believe.

**Pull request merged**
