### PR TITLE
KER-346 TextInput TextArea remove bootstrap

### PR DESCRIPTION
**Pull request by mikkojamG**
- TextArea & TextInput replace bootstrap, remove redundant InputBase
- TextArea & TextInput to function

### CODE REVIEW

**Comment by terovirtanen** [comment]
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1079-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://kerrokantasi-pr1079-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1079-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://kerrokantasi-pr1079-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by arpargo — APPROVED** [review]
LGTM

**Pull request merged**
