### PR TITLE
Upgrade (probably) safe-to-upgrade things

### PR DESCRIPTION
**Pull request by akx**
ℹ️  Nb: react-leaflet is pinned to 1.2.x due to newer versions having some trouble with FeatureGroup

* Use JS .eslintrc (for comments etc)
* As eslint plugins got updated, add rule exclusions that oughta be fixed later
* Get rid of eslint-loader (it can be done out-of-band anyway)
* Get rid of babel/babel-cli (they're not used, the core is enough)
* Add postcss.config.js to placate new postcss-loader
* Eslintignore flow-typed
* Update flow-typed cache (w/ --skip, so no unnecessary stubs are kept)

Test fixes:

* Fix usages of React.PropTypes
* Fix array keying in LabelList

### CODE REVIEW

**Comment by akx** [comment]
@Rikuoja Rebased on top of master :)

**Comment by akx** [comment]
@hukka Can you let me know what the new Snyk issue is? I can't access the report, because privileges.

**Comment by akx** [comment]
@vikoivun Can you be more specific about "breaks things"? 😄

**Comment by vikoivun** [comment]
Lots of complaints in the console and angry red boxes in the UI.

**Comment by akx** [comment]
Angry redness was caused by react-leaflet deciding to be upgraded to 1.6.x, which has some trouble with how kk-ui uses `<FeatureGroup />`. As a workaround it's now pinned to 1.2.x.

**Comment by Rikuoja** [comment]
For the record (for what it's worth), on my installation (regardless of yarn and node versions) I still keep getting the same build error:
```ERROR in ./src/index.js
Module build failed: ReferenceError: [BABEL] /Users/riku/Dropbox/Tyo/kerrokantasi-ui/src/index.js: Unknown option: /Users/riku/Dropbox/Tyo/kerrokantasi-ui/.babelrc.presets
```

**Comment by akx** [comment]
Rebased to get rid of conflict. Can someone merge, finally?

**Comment by Rikuoja** [comment]
Nope. I'm retracting my review.

Seems to break the baseurl/hearing_slug route when loading the page in development. Following a link from the front page works, but loading directly http://localhost:8086/frisbeegolf yields

```
ReferenceError: window is not defined
    at Sidebar.render (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/src/views/Hearing/Sidebar.js:200:21)
    at /Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:795:21
    at measureLifeCyclePerf (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:794:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:821:32)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:361:30)
    at ReactCompositeComponentWrapper.mountComponent (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
    at ReactCompositeComponentWrapper.mountComponent (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactDOMComponent.mountChildren (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactMultiChild.js:236:44)
    at ReactDOMComponent._createContentMarkup (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactDOMComponent.js:659:32)
    at ReactDOMComponent.mountComponent (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactDOMComponent.js:526:29)
    at Object.mountComponent (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
Trace
    at /Users/riku/Dropbox/Tyo/kerrokantasi-ui/server/render.js:127:15
    at process._tickCallback (internal/process/next_tick.js:109:7)
127.0.0.1 - - [25/Sep/2017:14:19:11 +0000] "GET /frisbeegolf HTTP/1.1" 500 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
2 ReferenceError: window is not defined
    at Sidebar.render (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/src/views/Hearing/Sidebar.js:200:21)
    at /Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:795:21
    at measureLifeCyclePerf (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:794:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:821:32)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:361:30)
    at ReactCompositeComponentWrapper.mountComponent (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
    at ReactCompositeComponentWrapper.mountComponent (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactDOMComponent.mountChildren (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactMultiChild.js:236:44)
    at ReactDOMComponent._createContentMarkup (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactDOMComponent.js:659:32)
    at ReactDOMComponent.mountComponent (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactDOMComponent.js:526:29)
    at Object.mountComponent (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/riku/Dropbox/Tyo/kerrokantasi-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
Trace
    at /Users/riku/Dropbox/Tyo/kerrokantasi-ui/server/render.js:127:15
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by akx** [comment]
I'm unable to reproduce that, @Rikuoja. I did exactly that -- `yarn dev`, then navigated to `http://localhost:8086/frisbeegolf`, and it loaded perfectly well.

**Comment by Rikuoja** [comment]
Smashing!

**Comment by Rikuoja** [comment]
FWIW, I did `yarn start`, so technically i'm not in dev mode I guess.

**Comment by akx** [comment]
Yeah, see, the difference between `yarn start` and `yarn dev` is that dev does not do SSR (by default).

Anyway, that's a bug that's not introduced by this PR – the Sidebar component blindly assumes that `window` is a thing, which it ain't when doing server-side rendering:

https://github.com/City-of-Helsinki/kerrokantasi-ui/blob/9eb40973b2e82dd32ac74742e4c65c93f9a69688/src/views/Hearing/Sidebar.js#L200

**Comment by akx** [comment]
@Rikuoja I added a commit (43c1c3c) that should work around that issue.

**Comment by Rikuoja** [comment]
Interestingly, it still works in production. Probably because SSR fails for an unknown reason.

**Comment by Rikuoja** [comment]
But yeah, on a tangential, seeing as SSR is giving us more pain than gain, we should consider not using it if it doesn't work.

**Comment by akx** [comment]
So are we in mergeable shape now, @Rikuoja?

Also, I can write a quick PR that rips out the current SSR implementation, but I'd rather only do that after this is merged. :)

**Comment by Rikuoja** [comment]
Oh, what the heck.

**Comment by akx** [comment]
> Oh, what the heck.

Oh, now you're thinking with modern JavaScript development!

**Pull request merged**
