### PR TITLE
fix: hearingContainer fetch metadata before projects KER-378

### PR DESCRIPTION
**Pull request by mikkojamG**
- HearingContainer fetch metadata before projects
- HearingContainer to function component (copied from KER-363)

### CODE REVIEW

**Comment by terovirtanen** [comment]
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1056-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://kerrokantasi-pr1056-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by arpargo — APPROVED** [review]
LGTM

**Comment by terovirtanen** [comment]
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1056-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://kerrokantasi-pr1056-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
