### PR TITLE
Changes needed because of backward incompatible API changes

### PR DESCRIPTION
**Pull request by tuomas777**
- introduction section is renamed to main

- hearing images are converted to main section images, hearings have
  also main_image field within their data

- hearing comments are converted to main section comments

ATTENTION requires the corresponding changes to be deployed on the backend!!

### CODE REVIEW

**Comment by akx** [comment]
Tbh these should all be separate commits and preferably they should have a "Refs" to the corresponding backend issue/PR/commit :)

**Comment by akx** [comment]
If you feel like separating the changes to atomic commits, then please do.

The code lgtm though.

**Comment by tuomas777** [comment]
I have a feeling that won't be going as in Strömsö, but I'll see what I can do :)

**Comment by tuomas777** [comment]
Updated, divided the commit to four commits

**Comment by akx** [comment]
Thanks 👍

**Pull request merged**
