### PR TITLE
fix: subsections should show comment if not authenticated KER-361

### PR DESCRIPTION
**Pull request by mikkojamG**
# KER-361

Subsections list should always show Comment button, even if subsection requires authentication.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1030-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://kerrokantasi-pr1030-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://kerrokantasi-pr1030-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by danipran — APPROVED** [review]
Seems to work :+1:
image

**Review by mrTuomoK — APPROVED** [review]
👍

**Pull request merged**
