### PR TITLE
Feature/horizontal sidebar

### PR DESCRIPTION
**Pull request by jonnetanninen**
Solves #423

### CODE REVIEW

**Comment by Rikuoja** [comment]
Though, of course, we still need `sectionGroups` for the `SectionBrowser`. But the main section will no longer display `sectionGroups` directly.

**Comment by jonnetanninen** [comment]
Do not merge this yet. I found some bugs that have popped up in unexpected places due to the interesting component structure of the software.

**Comment by Rikuoja** [comment]
Also, I'm thinking perhaps we should show several sections in the carousel on mid-sized mobile devices? The desktop and phone experience is fine, but a tablet would display the carousel with kinda confusingly empty space:

image

**Comment by Rikuoja** [comment]
Oh, and apparently also the carousel will have to check the current route when rendering :( Because currently, if switching the sections with the browser, the carousel remains unmoved so that the current section might not even be visible in the carousel.

**Comment by jonnetanninen** [comment]
Added scaling the amount of navigation items by screen width and added anchor links for more consistent navigation between sections. Latter is very hard to achieve, at least for the bottom of the section as we cannot place the anchor inside the content and the content height varies from one section to another...

**Comment by terotic** [comment]
Yes. Agree. Next/previous could jump to anchor point.

**Comment by Rikuoja** [comment]
Oh. One more thing.

There is a full screen Hearing (that has the Kartta koko näytöllä -button present) open all winter at kerrokantasi.hel.fi/talvipyoraily2017 .

Therefore, we will also have to support the case when there is a link to a full screen map plugin, much like the old Sidebar had the Kartta koko näytöllä -button.

This means that if a Hearing has a Plugin, we should render an extra button to the right to the main section, that takes us to the full screen map. Similar to the extra button to the left that displays the area map.

**Comment by Rikuoja** [comment]
The "Full screen map" button should have a suitable graphic that indicates that it will open the full screen map. Does @terotic have any idea what such a button would ideally look like? We don't really want to render the clickable map component there, though it does in theory support rendering in any size :)

**Comment by Rikuoja** [comment]
There is already a button at the bottom of the main section, but we should definitely add a similar button to the carousel itself, too:

image

**Comment by jonnetanninen** [comment]
How would it seem now?

**Comment by Rikuoja** [comment]
What says @terotic ? Now the carousel and the links at the bottom seem to work consistently, and so does the Full screen button in the carousel.

**Comment by Rikuoja** [comment]
However, two smaller issues that actually popped up in user testing yesterday.

1) There is no longer any need to display the section name type ("osa-alue"/"vaihtoehto"/"kilpailutyö"/whatnot) in the Edellinen/Seuraava buttons either. I guess showing this name comes from the old sidebar, which has the sections displayed and grouped by type.

As we no longer have section groups in sidebars, we can get rid of the whole section grouping and naming logic in my opinion. The backend might provide the name of the section (Osa-alue etc.), but we don't need to display it here anywhere anymore, as there is no header that shows the list in text.

So let's just change the buttons to "<Edellinen", "Seuraava>" in all views. I think this simplifies the code and we can get rid of some useless parts that managed the section groups and section names in sidebar and browser, if I'm not wrong?

2) There is still one functionality missing that was present in the old sidebar. That is, when the hearing has several languages, there should be the listing of hearing languages ("Kuuleminen suomeksi", "Hearing in English" etc.) in the Header, as the Sidebar that provided that no longer exists.

Therefore, let's dig the removed Sidebar code for `getLanguageChanger` (https://github.com/City-of-Helsinki/kerrokantasi-ui/blob/master/src/views/Hearing/Sidebar.js#L91 ) and put it in the Header (all languages in one line). My suggestion would be to put it in the bottom right of the Header, on the same line as the social links, as there is ample free space:

image

However, perhaps @terotic has a better idea on what is the ideal location for the Hearing language changer? The languages should be, I believe, separated the same way as in the UI language changer: "Kuuleminen suomeksi | Hearing in English"

**Comment by jonnetanninen** [comment]
Now should be mergable

**Pull request merged**
