### PR TITLE
Subsection links to sidebar

### LINKED ISSUE #243: Display section headlines below sections in the left bar, to make navigating within a hearing easier?

### PR DESCRIPTION
**Pull request by vaaralav**
Fixes #243 .
~Depends on PR #281 .~

- [x] Sidebar scrolling problems when sidebar is taller than viewport
- [x] Fixed nav covers elements with `#` linking
- [ ] Don't scroll sidebar separately, but keep sidebar always visible.
- [ ] Limit sidebar height only when footer is visible

### CODE REVIEW

**Comment by vaaralav** [comment]
- [ ] Sidebar scrolling problems when sidebar is taller than viewport
- [ ] Fixed nav covers elements with `#` linking

**Comment by Rikuoja** [comment]
Currently, the sidebar displayed is actually not as tall as the page itself. Ideally, the sidebar would extend to the bottom of the screen as it currently does. 
image

**Comment by Rikuoja** [comment]
In addition, scrolling the sidebar separately from the main page results in rather funny behavior, in which only top of the sidebar may be visible even if we have scrolled the main page downwards. Similarly, only the bottom of the sidebar may be visible at the top of the page, if we have hit the sidebar while scrolling up and down.

image

Ideally, the sidebar would scroll up and down along with the page itself, but stop scrolling once we have hit the bottom of the sidebar. I couldn't figure out if it's possible to do this with css.

**Comment by vaaralav** [comment]
Decided to do #243 and #289 together: https://github.com/vaaralav/kerrokantasi-ui/tree/feature/%23289-%23243-refactor-hearing-navigation

**Pull request closed without merging**
