### PR TITLE
[WIP] Perform logout by taking user through tunnistamo logout page

### PR DESCRIPTION
**Pull request by vikoivun**
Makes logout actually do a logout at tunnistamo. This would not previously work, as tunnistamo does not allow fetch access to the logout endpoint.

Note that this is still hardcoded for tunnnistamo-test.

### CODE REVIEW

**Comment by Rikuoja** [comment]
@vikoivun Is there still something unfinished in this PR? Apparently a timeout problem remains?

**Comment by Rikuoja** [comment]
@vikoivun Is this still unfinished? I believe this should be implemented in all of our clients?

**Comment by vikoivun** [comment]
> @vikoivun Is this still unfinished? I believe this should be implemented in all of our clients?

The action has moved to tunnistamo side. We've found a standardized (OIDC) logout-endpoint and that is in the process of being spruced (or perhaps pined) out.

**Comment by Rikuoja** [comment]
Okay, so does kerrokantasi use that endpoint yet? What needs to be done?

**Comment by vikoivun** [comment]
The poor page has gotten dropped to the ditch. We need to decide if it is really wanted, and if so, finish the implementantion on tunnistamo side.

**Pull request closed without merging**
