### PR TITLE
KER-330 attachment fix

### PR DESCRIPTION
**Pull request by arpargo**
Fix to uploading attachments to hearing.

Component was not receiving the language from this.context, reason most likely being react version upgrades earlier.

Changed to use language from store.

Implemented change to all other places using this.context as it most likely was silently broken in those places aswell.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1008-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://kerrokantasi-pr1008-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by mikkojamG — APPROVED** [review]
👍

**Comment by terovirtanen** [comment]
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1008-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://kerrokantasi-pr1008-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
