### PR TITLE
Feature/smoke tests

### PR DESCRIPTION
**Pull request by jonnetanninen**
Solves #418 . 

The philosophy is to add snapshot tests with static mock date for the most important components as a "smoke test". This approach was approved and suggested by our lead developers. Later there is possibility to test certain functionalities separately and apply unit & integration tests, but I don't think it should be done in this phase as this PR would grow super large.

At the moment some of the tests are little bit questionable as the components tested are huge and super complex. To allow better tests and make testing easier, extensive refactoring would be required.

### CODE REVIEW

**Comment by Rikuoja** [comment]
Oh, rebase needed on dependencies though.

**Comment by Rikuoja** [comment]
One test that is more difficult to implement would be trying out what happens when the user tries to post a new comment in comment list.

This test would try out if the pipe from hearing sections all the way to posting a comment is correct. However, the result would require a mock API to display the comment back :/

**Comment by jonnetanninen** [comment]
Rebased

**Comment by jussiarpalahti** [comment]
@Rikuoja Is there particular reason we're not running tests through travis?

Can't we do so after this gets merged?

**Comment by akx** [comment]
@jussiarpalahti Um... tests _are_ being run in Travis? https://travis-ci.org/City-of-Helsinki/kerrokantasi-ui/builds/303494223

**Comment by jussiarpalahti** [comment]
Achoo.. Travis report was hidden behind that green thing among other green things.. I blame github.

All is well then 😁

**Comment by Rikuoja** [comment]
Alas! Rebase needed!

**Comment by jussiarpalahti** [comment]
Hm. I wonder why this wasn't mergeable? Perhaps it's just the order of changes that looks like a problem for git?

**Comment by Rikuoja** [comment]
Most likely the snyk dependency or something else I just added caused the problem? :D

**Comment by jussiarpalahti** [comment]
Arg.. Didn't scroll far enough :/
Snyk and this PR both change last lines of package.json
Oh well, it should be relatively trivial to merge..

**Comment by jussiarpalahti** [comment]
Hrm. Github doesn't allow rebasing conflict resolution commit. Or I can't understand that part of the UI either. Oh well..

**Pull request merged**
