### PR TITLE
Clear message text field after submit

### PR DESCRIPTION
**Pull request by JsseL**
According to issue #174 preserved text in comment box is causing
bad usability.

After comment submit remove the text

Refs: #174

### CODE REVIEW

**Comment by akx** [comment]
If the submission fails, the user will have lost their comment. :(

**Comment by Rikuoja** [comment]
Granted, the clear should be done only when submit succeeds and we are reloading.

**Comment by JsseL** [comment]
This required some helping hand from the dark master.

**Comment by akx** [comment]
I prefer the epithet "dork master".

**Comment by akx** [comment]
@JsseL Ah, we need to turn

```javascript
(window.devToolsExtension ? window.devToolsExtension() : identity)
```
into
```javascript
(typeof window !== 'undefined' && window.devToolsExtension ? window.devToolsExtension() : identity)
```

**Comment by JsseL** [comment]
Pair coded the solution with @akx so to us this is ready to be shipped. Project doesn't have any UI functionality testing so coverage decrease can either be ignored or we can start doing some functionality testing too, if it is seen worthwhile.

@riku your call.

**Comment by JsseL** [comment]
Some reason why we wouldn't merge this already?

**Comment by Rikuoja** [comment]
Looking good!

**Pull request merged**
